download:
  python utils/dataset.py

load:
  python utils/schema.py

embed:
  python utils/embeddings.py

fts:
  python utils/fts.py

fts_search:
  python utils/fts_search.py "your query"

vss_search:
  python utils/vss.py "your query"
